version: "3"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    links:
      - db
    volumes:
      - .:/tweet-app
      - node_modules:/app/node_modules
    tty: true
    stdin_open: true

  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: 'trust'
volumes:
  db:
  node_modules:
